INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (1, 'Análise e Projeto de Sistemas I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (2, 'Matemática I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (3, 'Química II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (4, 'Artes', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (5, 'Geografia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (6, 'Física I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (7, 'História I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (8, 'Filosofia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (9, 'Sociologia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (10, 'Filosofia II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (11, 'Educação Física I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (12, 'Lógica de Programação', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (13, 'Língua Espanhola I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (14, 'Inglês Técnico I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (15, 'Língua Portuguesa e Literatura I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (16, 'Introdução à Informática', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (17, 'Sistemas Operacionais', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (18, 'Linguagens para Internet', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (19, 'Língua Espanhola II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (20, 'Matemática II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (21, 'Banco de Dados I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (22, 'Geografia IV', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (23, 'História IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (24, 'Biologia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (25, 'Programação I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (26, 'Geografia II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (27, 'História II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (28, 'Química I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (29, 'Educação Física II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (30, 'Língua Portuguesa e Literatura II', now(), now());	
