INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (1, 'Análise e Projeto de Sistemas I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (2, 'Análise e Projeto de Sistemas II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (3, 'Matemática I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (4, 'Matemática II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (5, 'Matemática III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (6, 'Matemática IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (7, 'Química I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (8, 'Química II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (9, 'Química III', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (10, 'Artes', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (11, 'Geografia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (12, 'Geografia II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (13, 'Geografia III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (14, 'Geografia IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (15, 'Física I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (16, 'Física II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (17, 'Física III', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (18, 'História I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (19, 'História II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (20, 'História III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (21, 'História IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (22, 'Filosofia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (23, 'Filosofia II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (24, 'Filosofia III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (25, 'Filosofia IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (26, 'Sociologia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (27, 'Sociologia II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (28, 'Sociologia III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (29, 'Sociologia IV', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (30, 'Educação Física I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (31, 'Educação Física II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (32, 'Lógica de Programação', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (33, 'Língua Espanhola I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (34, 'Língua Espanhola II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (35, 'Língua Espanhola III', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (36, 'Inglês Técnico I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (37, 'Inglês Técnico II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (38, 'Inglês Técnico III', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (39, 'Língua Portuguesa e Literatura I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (40, 'Língua Portuguesa e Literatura II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (41, 'Língua Portuguesa e Literatura III', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (42, 'Língua Portuguesa e Literatura IV', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (43, 'Introdução à Informática', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (44, 'Sistemas Operacionais', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (45, 'Linguagens para Internet', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (46, 'Banco de Dados I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (47, 'Banco de Dados II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (48, 'Biologia I', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (49, 'Biologia II', now(), now());	
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (50, 'Biologia III', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (51, 'Programação I', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (52, 'Programação II', now(), now());
INSERT INTO disciplines (id, name, created_at, updated_at) VALUES (53, 'Programação III', now(), now());